<div id="cont">
	<div class="page-header">
	    <h3>
	        Eliminar alumnos
	    </h3>
	</div>

	<div class="form-group">
	    <label for="fieldNombre" class="col-sm-2 control-label">Id</label>
	    <div class="col-sm-10">
	        <?php echo $this->tag->textField([
	            "eliminar", 
	            "size"  => 30, 
	            "class" => "form-control", 
	            "id"    => "alumno_id"
	        ]) ?>
	    </div>
	</div>

	<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button onclick="al(4)" id="btn_reg_alu" class="btn btn-default">Eliminar</button>
    </div>
</div>
</div>