<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search alumnos
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["alumnos/new", "Create alumnos"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "alumnos/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCodalu" class="col-sm-2 control-label">Codalu</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codalu", "size" => 30, "class" => "form-control", "id" => "fieldCodalu"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNomalu" class="col-sm-2 control-label">Nomalu</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nomalu", "size" => 30, "class" => "form-control", "id" => "fieldNomalu"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCaralu" class="col-sm-2 control-label">Caralu</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["caralu", "size" => 30, "class" => "form-control", "id" => "fieldCaralu"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
