<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<style type="text/css">
    #cont {
        width: 500px;
    }
</style>

<div id="cont">
<div class="page-header">
    <h3>
        Registrar alumnos
    </h3>
</div>

<?php echo $this->getContent(); ?>

<div class="form-group">
    <label for="fieldNombre" class="col-sm-2 control-label">Nombre</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField([
            "nombre", 
            "size"  => 30, 
            "class" => "form-control", 
            "id"    => "fieldNombre"
        ]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldApellido" class="col-sm-2 control-label">Apellido</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField([
            "apellido", 
            "size"  => 30, 
            "class" => "form-control", 
            "id"    => "fieldApellido"
        ]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCorreo" class="col-sm-2 control-label">Correo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField([
            "correo", 
            "size"  => 30, 
            "class" => "form-control", 
            "id"    => "fieldCorreo"
        ]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTelefono" class="col-sm-2 control-label">Telefono</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField([
            "telefono", 
            "size"  => 30, 
            "class" => "form-control", 
            "id"    => "fieldTelefono"
        ]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDireccion" class="col-sm-2 control-label">Direccion</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField([
            "direccion", 
            "size"  => 30, 
            "class" => "form-control", 
            "id"    => "fieldDireccion"
        ]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button onclick="al(2)" id="btn_reg_alu" class="btn btn-default">Registrar</button>
    </div>
</div>

</div>