<link rel="stylesheet" type="text/css" href="/css/estilo.css">
<script type="text/javascript">
    //console.log(localStorage.getItem("sesion_token"));
</script>
<div class="container">
    <div class="login-form">
        <div class="main-div">
            <div class="panel">
                <h2>Trabajo Final empresariales</h2>
            </div>
            <div class="form-group">
                <input required type="email" class="form-control" name="usuario" id="inputEmail" placeholder="Tu correo">
            </div>
            <div class="form-group">
                <input required type="password" class="form-control" name="contraseña" id="inputPassword" placeholder="Tu Password">
            </div>
            <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>' value='<?php echo $this->security->getToken() ?>'/>
            <button onclick="Login(url_base + '/login')" class="btn btn-primary">Iniciar</button>
        </div>
    </div>
</div>
