<?php
    session_start();
    $sesion = $this->getDI()->getShared("session"); 
?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Trabajo Final Empresariales</title>
        <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico"/>
        <script src="/js/jquery.js"></script>
        <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>   
        <link href="/css/simple-sidebar.css" rel="stylesheet" type="text/css">
        <script src="/vendor/jquery/jquery.min.js"></script>
        <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script type="text/javascript">
            var datos;
            var getUrl = window.location;
            var url_base = getUrl.protocol + "//" + getUrl.host;
            console.log("uno: " + (getUrl + "") + " dos: " + url_base + "/");
        </script>
        <script type="text/javascript" src="js/func.js"> </script>
        <script type="text/javascript">
            console.log(localStorage.getItem("sesion_token"));
            if(localStorage.getItem("sesion_token") == null) {
                if ((getUrl + "").localeCompare(url_base + "/login-v") != 0) {
                    window.location.replace(url_base + "/login-v");
                } 
            } else {
                if ((getUrl + "").localeCompare(url_base + "/") == 0) {
                    window.location.replace(url_base + "/home");
                } else if ((getUrl + "").localeCompare(url_base + "/login-v") == 0) {
                    window.location.replace(url_base + "/home");
                }
            }
        </script>
    </head>
    <body>
        <div class="modal fade" id="info_modal_id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h6 class="modal-title" id="titulomodal"></h6>
                    </div>
                    <div id="textmodal" class="modal-body">
                        
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Aceptar</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal -->    
        <?php echo $this->getContent(); ?>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
 
    </body>
</html>
